M48
; DRILL file {KiCad 8.0.4} date 2024-11-26T20:16:59-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-26T20:16:59-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X57.135Y-157.595
X57.135Y-162.445
T2
X54.105Y-157.295
X54.105Y-162.745
T3
X147.32Y-50.8
M30
